baseURL = "https://seanxp.com/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "SeanXP's Blog"
keywords = ["SeanXP", "Blog", "Programme", "Backend"]

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "DoIt"
dateFormat = "2006-01-02"

# 作者配置
[author]
name = "SeanXP"
email = "iseanxp+blog@gmail.com"
link = ""
avatar = ""
gravatarEmail = ""

[params]
# DoIt 主题版本
version = "0.4.0"

[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "关于"
    url = "about"
    title = ""
    weight = 4

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark.renderer]
  unsafe = true

# 页面头部导航栏配置
[params.header]
# DoIt 新增 | 0.2.11 主题切换模式
# 主题切换模式 ("switch", "select")
themeChangeMode = "switch"

# 页面底部信息配置
[params.footer]
enable = true
# DoIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
custom = ''
# DoIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
hugo = true
# DoIt 新增 | 0.2.14 托管服务信息 (支持 HTML 格式)
# <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
hostedOn = ''
# DoIt 新增 | 0.2.0 是否显示版权信息
copyright = true
# DoIt 新增 | 0.2.0 是否显示作者
author = true
# 网站创立年份
since = 2015
# ICP 备案信息, 仅在中国使用 (支持 HTML 格式)
icp = ""
# 许可协议信息 (支持 HTML 格式)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# 用于 Hugo 输出文档的设置
[outputs]
# DoIt 更改 | 0.2.0
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]

# 用于分类的设置
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"

[params.search]
enable = true
# 搜索引擎的类型 ("algolia", "fuse")
type = "fuse"
# 文章内容最长索引长度
contentLength = 4000
# 搜索框的占位提示语
placeholder = ""
#  最大结果数目
maxResultLength = 10
#  结果内容片段长度
snippetLength = 50
#  搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
#  是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = false
[params.search.algolia]
index = ""
appID = ""
searchKey = ""
[params.search.fuse]
#  https://fusejs.io/api/options.html
isCaseSensitive = false
minMatchCharLength = 2
findAllMatches = false
location = 0
threshold = 0.3
distance = 100
ignoreLocation = false
useExtendedSearch = false
ignoreFieldNorm = false

# DoIt 新增 | 0.2.0 Section (所有文章) 页面配置
[params.section]
# section 页面每页显示文章数量
paginate = 30
# 日期格式 (月和日)
dateFormat = "2006-01-02"
# RSS 文章数目
rss = 10
# DoIt 新增 | 0.2.13 最近更新文章设置
[params.section.recentlyUpdated]
enable = false
rss = false
days = 30
maxCount = 10

# DoIt 新增 | 0.2.0 List (目录或标签) 页面配置
[params.list]
# list 页面每页显示文章数量
paginate = 20
# 日期格式 (月和日)
dateFormat = "2006-01-02"
# RSS 文章数目
rss = 10

# 主页配置
[params.home]
# DoIt 新增 | 0.2.0 RSS 文章数目
rss = 10
# 主页个人信息
[params.home.profile]
enable = true
# Gravatar 邮箱, 用于优先在主页显示的头像
gravatarEmail = ""
# 主页显示头像的 URL
# 将你的头像文件放置于 static 或者 assets 目录下
# 文件路径是相对于 static 或者 assets 目录的
avatarURL = "avatar.png"
# 头像的链接指向的 URL
avatarLinkURL = ""
# DoIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
title = ""
# 主页显示的网站副标题
#subtitle = "为学日益，为道日损，损之又损，以至于无为，无为而无不为。"
# 是否为副标题显示打字机动画
typeit = true
# 是否显示社交账号
social = true
# DoIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
disclaimer = ""

# 主页文章列表
[params.home.posts]
enable = true
# 主页每页显示文章数量
paginate = 10

# 作者的社交信息设置
[params.social]
GitHub = "SeanXP"
#Douban = "SeanXP"
Email = "iseanxp@gmail.com"
RSS = true

# DoIt 更改 | 0.2.0 文章页面配置
[params.page]
# DoIt 新增 | 0.2.0 是否在主页隐藏一篇文章
hiddenFromHomePage = false
# DoIt 新增 | 0.2.0 是否在搜索结果中隐藏一篇文章
hiddenFromSearch = false
# DoIt 新增 | 0.2.0 是否使用 twemoji
twemoji = false
# 是否使用 lightgallery
lightgallery = false
# DoIt 新增 | 0.2.0 是否使用 ruby 扩展语法
ruby = true
# DoIt 新增 | 0.2.0 是否使用 fraction 扩展语法
fraction = true
# 是否在文章页面显示原始 Markdown 文档链接
linkToMarkdown = true
# DoIt 新增 | 0.2.14 配置文章原始文件的链接
linkToSource = false
# "https://github.com/user/repo/blob/main/{path}"
# DoIt 新增 | 0.2.13 配置编辑文章的链接
linkToEdit = false
# "https://github.com/user/repo/edit/main/{path}"
# "https://gitlab.com/user/repo/-/edit/main/{path}"
# "https://bitbucket.org/user/repo/src/main/{path}?mode=edit"
# DoIt 新增 | 0.2.14 配置提交错误的链接
linkToReport = false
# "https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
# DoIt 新增 | 0.2.4 是否在 RSS 中显示全文内容
rssFullText = true
# DoIt 新增 | 0.2.13 是否在文章开头显示系列导航
seriesNavigation = true
# 是否启用最后修改时间
enableLastMod = true
# 是否启用字数统计
enableWordCount = true
# 是否启用阅读时间估计
enableReadingTime = true
# DoIt 新增 | 0.2.13 过时文章提示
[params.page.outdatedArticleReminder]
enable = false
# 如果文章最后更新于 90 天之前，显示提醒
reminder = 90
# 如果文章最后更新于 180 天之前，显示警告
warning = 180
# DoIt 新增 | 0.2.0 目录配置
[params.page.toc]
# 是否使用目录
enable = true
# DoIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
keepStatic = true
# 是否使侧边目录自动折叠展开
auto = true
# DoIt 新增 | 0.2.0 代码配置
[params.page.code]
# 默认展开显示的代码行数
maxShownLines = 10
# DoIt 新增 | 0.2.14 表格配置
[params.page.table]
# 是否开启表格排序
sort = true
# DoIt 更改 | 0.2.0 KaTeX 数学公式
[params.page.math]
enable = true
# 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
blockLeftDelimiter = ""
blockRightDelimiter = ""
# 默认行内定界符是 $ ... $ 和 \\( ... \\)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
# KaTeX 插件 copy_tex
copyTex = true
# KaTeX 插件 mhchem
mhchem = true
# 使用 MathJax 替代 KaTeX
mathjax = false
# DoIt 新增 | 0.2.0 Mapbox GL JS 配置
[params.page.mapbox]
# Mapbox GL JS 的 access token
accessToken = ""
# 浅色主题的地图样式
lightStyle = "mapbox://styles/mapbox/light-v9"
# 深色主题的地图样式
darkStyle = "mapbox://styles/mapbox/dark-v9"
# 是否添加 NavigationControl
navigation = true
# 是否添加 GeolocateControl
geolocate = true
# 是否添加 ScaleControl
scale = true
# 是否添加 FullscreenControl
fullscreen = true

# DoIt 更改 | 0.2.0 文章页面的分享信息设置
[params.page.share]
enable = false
Twitter = true
Facebook = true

# instant.page 设置
[params.page.instantpage]
enable = false

# DoIt 更改 | 0.2.0 评论系统设置
[params.page.comment]
enable = true
# DoIt 新增 | 0.2.5 Utterances 评论系统设置
[params.page.comment.utterances]
enable = true
# owner/repo
repo = "SeanXP/seanxp-blog"
issueTerm = "pathname"
label = ""
lightTheme = "github-light"
darkTheme = "github-dark"

# DoIt 新增 | 0.2.0 网站分析配置
[params.analytics]
enable = false

# 网站地图配置
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# Permalinks 配置
[Permalinks]
# posts = ":year/:month/:filename"
posts = ":filename"

# 用于输出 Markdown 格式文档的设置
[mediaTypes]
[mediaTypes."text/plain"]
suffixes = ["md"]

# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
mediaType = "text/plain"
isPlainText = true
isHTML = false
